# SonarCloud Configuration
sonar.projectKey=fpmi-hci-2025_project13-backend-bookstore
sonar.organization=fpmi-hci-2025

# Project metadata
sonar.projectName=BookStore Backend
sonar.projectVersion=1.0.0

# Source code location
sonar.sources=.
sonar.exclusions=**/*_test.go,**/vendor/**,**/docs/**,**/*.pb.go

# Test files
sonar.tests=.
sonar.test.inclusions=**/*_test.go

# Coverage report
sonar.go.coverage.reportPaths=coverage.out

# Language
sonar.language=go

# Encoding
sonar.sourceEncoding=UTF-8

